#!/bin/bash
echo "ibase=water; $WATER" | tr 'water' '0123456789 | tr -d '\n' ; echo "+" ; echo "ibase=stir; $STIR" | tr 'stir' '0123456789' | tr -d '\n' | echo "$(cat -)"; echo "quit" | bc | tr '0123456789' 'bestchol'
